spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/aad_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.jdbc.core: DEBUG

aad:
  sql:
    scripts:
      - classpath:sql/ddl/01_schema.sql
      - classpath:sql/ddl/02_procedures.sql
      - classpath:sql/ddl/03_sample_data.sql
